---
galaxy_info:
  role_name: dokploy
  author: Open Mercato
  description: Install and configure Dokploy on Ubuntu servers
  license: MIT
  min_ansible_version: "2.14"

  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble

  galaxy_tags:
    - docker
    - dokploy
    - deployment
    - paas

dependencies: []
